## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url: https://uaplitclub.github.io # Your website URL
baseurl: "" # The base URL path, leave empty if hosted on the root path
title: UAP Literary Club
description: > # this means to ignore newlines until "Language & timezone"
  A vibrant community for literature enthusiasts at UAP.

## => Logo Configuration
logo: /assets/ulc-logo.png # Correct path to your logo image

## => Language and Timezone
##############################
lang: "en" # Language of your site
timezone: "Asia/Dhaka" # Set your timezone

## => Author and Social
##############################
author:
  type: "organization" # Organization (UAP Literary Club)
  name: "UAP Literary Club"
  url: "https://uaplitclub.github.io"
  avatar: "/assets/images/avatar.jpg" # Path to avatar image (square)
  bio: "A vibrant community for literature enthusiasts at UAP."
  email: "contact@uaplitclub.com"
  facebook: "uaplitclub"
  twitter: "uaplitclub"
  github: "uaplitclub"
  linkedin: "uaplitclub"

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: uaplitclub/uaplitclub.github.io
repository_tree: master

## => Paths
##############################
paths:
  root: "/" # Root path link
  home: "/" # Home layout url
  archive: "/archive.html" # Archive layout url
  rss: "/feed.xml" # RSS feed URL

## => Post
##############################
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # License type

## TOC
toc:
  selectors: "h1,h2,h3" # Table of contents selectors

## => Markdown Enhancements
##############################
mathjax: false
mermaid: false
chart: false

## => Paginate
##############################
paginate: 8
paginate_path: "/page:num"

## => Sources
##############################
sources: "bootcdn" # or unpkg

## => Sharing
##############################
sharing:
  provider: false # You can use "addtoany" or "addthis" for sharing

## => Comments
##############################
comments:
  provider: false # You can use "disqus", "gitalk", "valine"

## => Pageview
##############################
pageview:
  provider: false # You can use "leancloud" for pageviews

## => Analytics
##############################
analytics:
  provider: false # You can use "google" for analytics

## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - LICENSE
  - README.md
  - /docs
  - /node_modules
  - /test

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
